### PR TITLE
Test meta relation for extended User model

### PR DESCRIPTION
**Pull request by Dartui**
See #307 for more informations

### CODE REVIEW

**Comment by jgrossi** [comment]
Thanks for the PR. Your new test case is not passing. Can you fix that please?

**Comment by Dartui** [comment]
I know, this is only test-case to show what is going on in #307. Should I put here possible solution for that?

**Comment by jgrossi** [comment]
@Dartui can you fix it please?

**Comment by Dartui** [comment]
Code moved to #338

**Pull request closed without merging**
