### PR TITLE
Add laravel 5.5 compatibilty

### PR DESCRIPTION
**Pull request by florianflock**

### CODE REVIEW

**Comment by florianflock** [comment]
@jgrossi - need this for a project. :)
Can you check your acf repo also please?

Would be nice, thanks!

**Comment by Dartui** [comment]
@florianflock could you resolve problem which travis-ci reported?

**Comment by florianflock** [comment]
Maybe he wants a exact version? v5.5.1?

**Comment by jgrossi** [comment]
Hi @florianflock thanks for the PR. Actually for Laravel 5.5 we have to change a lot of things, like the `Model` class and its relations, I think are not necessary anymore. We have to make sure all tests are passing before merging.

**Pull request closed without merging**
