### PR TITLE
Readme Update

### PR DESCRIPTION
**Pull request by firescript**
1. I added a table of contents 
2. explained in more depth how to install corcel, wordpress into laravel
3. explained database set up options, 1 db or 2 db and what it takes to have either
4. Moved down the usage section
5. Fixed a couple typos and grammar things.

Just my thoughts on how we could make it easier to understand for new people coming here.

### CODE REVIEW

**Comment by jgrossi** [comment]
Hi @firescript! First, thanks for contributing. There're a lot of changes here haha. I'm gonna take a look and give you a feedback soon :-) I think just a couple of changes/typos to fix, but that structure is so much better than before, thanks!

Maybe I can do some changes I think that are necessary and push to your own repo :-)

**Comment by firescript** [comment]
Yeah that works for me @jgrossi 

Fix what ever you think needs to be fixed and we can go from there. Great work on this project, I'm using it on my latest client project so I wanted to contribute in some way right now.

**Comment by jgrossi** [comment]
Thanks @firescript. We have a lot of job to do yet, then any contribution is appreciated :-)

**Comment by jgrossi** [comment]
@firescript Please take a look on some changes I've made and let me know what you think. I already committed to your `patch-1` branch.

https://github.com/corcel/corcel/pull/265/commits/a5729ba0d89046012d0b427572eb08c0892d0f03

**Comment by firescript** [comment]
Looks good, you know the system best. Just wanted to make it a bit clearer, especially regarding the wordpress installation part. Made a couple typo tweaks and small changes, up to you if you want to keep them.

**Comment by jgrossi** [comment]
[Review README changes](https://trello.com/c/rY1vyDGd/6-review-readme-changes)

**Comment by jgrossi** [comment]
@firescript thanks for this and sorry about the late merge ;-)

**Pull request merged**
