### PR TITLE
Added WordPress post formatting

### PR DESCRIPTION
**Pull request by goodbytes-gb**
Added WordPress post formatting class accessible via getFormattedContentAttribute() accessor and moved 'get content' into it's own method so it could be reused in both get post content accessor methods.

### CODE REVIEW

**Comment by jgrossi** [comment]
Hey @goodbytes-gb thanks for helping. I noticed you copied the `wpautop` function from WordPress. We have first to check if this is allowed according to WordPress rules. BTW the Corcel branch is wrong, please change it to `dev` instead of `master`.

**Comment by goodbytes-gb** [comment]
Hi, yes a lot of the functionality is taken from WP to mimic the output as much as possible. Will change branch to `dev`

**Comment by cyannick** [comment]
Hi @jgrossi, any updates on this issue?

**Comment by goodbytes-gb** [comment]
Yes, it would be good to get this merged in, I'm still using a customised version.

It uses a variant of WP code, obviously, as we're trying to get the same sort of output, I'm not aware of any rules for using their code, if I could be point in the right direction I will run it by them.

**Comment by jgrossi** [comment]
@cyannick @goodbytes-gb the point here is I cannot use that code. It's copied from the WP source code, and it's license does not allow that, unfortunately. Even if allowed the code is not clear, it should be refactored.

Just to make sure the code is copied, here is a diff from the original one and yours:

http://www.mergely.com/FVorMikR/

**Comment by goodbytes-gb** [comment]
I will refactor the code and re-submit for your consideration.

**Comment by jgrossi** [comment]
@goodbytes-gb sounds good

**Comment by goodbytes-gb** [comment]
No longer necessary, please see #292

**Pull request closed without merging**
